<?php
namespace app\admin\script\analysis;

use app\admin\script\analysis\activity\UserRoomActivityDataByRegChannel;
use app\admin\script\analysis\agentpay\UserAgentPayDataByRegChannel;
use app\admin\script\analysis\charge\UserChargeDataByRegChannel;
use app\admin\script\analysis\diamond\UserDiamondDataByRegChannel;
use app\admin\script\analysis\gift\UserRoomSendGiftDataByRegChannel;
use app\admin\script\analysis\login\UserLoginDataByRegChannel;
use app\admin\script\analysis\redpackage\UserRedPackageDataByRegChannel;
use app\admin\script\analysis\withdraw\UserWithdrawDataByRegChannel;

class AnslysisConst
{
    const LIMIT = 1000;
    const CLASS_MAP = [
        // 'register' => '',
        'login' => UserLoginDataByRegChannel::class,
        'charge' => UserChargeDataByRegChannel::class,
        'agentcharge' => UserAgentPayDataByRegChannel::class,
        // 'firstcharge' => UserLoginDataByRegChannel::class,
        'sendGift' => UserRoomSendGiftDataByRegChannel::class,
        'receiveGift' => UserRoomSendGiftDataByRegChannel::class,
        'activity' => UserRoomActivityDataByRegChannel::class,
        'sendRed' => UserRedPackageDataByRegChannel::class,
        'receiveRed' => UserRedPackageDataByRegChannel::class,
        'returnRed' => UserRedPackageDataByRegChannel::class,
        'diamond' => UserDiamondDataByRegChannel::class,
        'withdraw' => UserWithdrawDataByRegChannel::class,
    ];

    const CHANNEL = [
        'appStore',
        'Oppo',
        'GW',
        'HuaWei',
        'XiaoMi',
        'Vivo',
        'Q360',
        'YingYongBao',
        'Ali',
        'yidong2',
        'yidong1',
        'zhangyue',
        'MaiZu',
        'BaiDu',
        'MaXiaoEr',
        'KuaiShowDanDan',
        'WanDouJia',
        'KuaiShowDanDan01',
        'QQtf',
        'KuaiShowDanDan04',
        'BeiWanJLYQ01',
        'KuaiShowDanDan05',
        'KuaiShowDanDan06',
        'QingGe',
        'KuaiShowDanDan07',
        'Lenovo',
        'KuaiShowDanDan09',
        'KuaiShowDanDan08',
        'KuaiShowDanDan12',
        'KuaiShowDanDan13',
        'KuaiShowDanDan02',
        'KuaiShowDanDan03',
        'KuaiShowDanDan10',
        'KuaiShowDanDan15',
        'YingYongB',
        'BeiWanKuaiShou01',
        'KuaiShowDanDan11',
        'KuaiShowDanDan14',
        'KuaiShowDanDan16',
        'KuaiShowDanDan20',
        'KuaiShowDanDan23',
        'LingDongTS',
        'KuaiShowDanDan18',
        'LingDongBZ01',
        'LingDongBZ02',
        'LingDongBZ04',
        'BeiWanKuaiShou02',
        'LingDongBZ03',
        'LingDongBZ05',
        'KuaiShowDanDan26',
        'KuaiShowDanDan32',
        'KuaiShowDanDan44',
        'KuaiShowDanDan42',
        'KuaiShowDanDan41',
        'ZhiXiangKS01',
        'KuaiShowDanDan25',
        'KuaiShowDanDan27',
        'KuaiShowDanDan37',
        'KuaiShowDanDan38',
        'ZhiXiangKS13',
        'ZhiXiangKS14',
        'ZhiXiangKS15',
        'ZhiXiangKS04',
        'ZhiXiangKS03',
        'KuaiShowDanDan39',
        'ZhiXiangKS05',
        'ZhiXiangKS17',
        'ZhiXiangKS16',
        'KuaiShowDanDan45',
        'ZhiXiangKS49',
        'ZhiXiangKS32',
        'ZhiXiangKS21',
        'ZhiXiangKS02',
        'ZhiXiangKS06',
        'ZhiXiangKS08',
        'ZhiXiangKS07',
        'ZhiXiangKS11',
        'ZhiXiangKS20',
        'ZhiXiangKS18',
        'KuaiShowDanDan28',
        'ZhiXiangKS12',
        'ZhiXiangKS19',
        'BeiWanKuaiShou04',
        'ZhiXiangKS40',
        'ZhiXiangKS39',
        'ZhiXiangKS37',
        'ZhiXiangKS42',
        'DeXuanZuiYouTS',
        'ZhiXiangKS09',
        'DeXuanZuiYou01',
        'DeXuanZuiYou08',
        'DeXuanZuiYou05',
        'DeXuanZuiYou09',
        'ZhiXiangKS50',
        'TuSiKuaiShou02',
        'TuSiKuaiShou06',
        'TuSiKuaiShou10',
        'PinZhongKuaiShouTS',
        'DeXuanZuiYou04',
        'ZhiXiangKS48',
        'DeXuanZuiYou02',
        'DeXuanZuiYou06',
        'ZhiXiangKS43',
        'ZhiXiangKS44',
        'PengLaiYingKuaiShou01',
        'PengLaiYingKuaiShou08',
        'PengLaiYingKuaiShou03',
        'DeXuanZuiYou07',
        'DeXuanZuiYou03',
        'ZhiXiangKS31',
        'ZhiXiangKS38',
        'ZhiXiangKS36',
        'ZhiXiangKS10',
        'ZhiXiangKS46',
        'ZhiXiangKS41',
        'PinZhongKuaiShouKS',
        'ZhiXiangKS25',
        'ZhiXiangKS24',
        'ZhiXiangKS45',
        'ZhiXiangKS23',
        'ZhiXiangKS33',
        'ZhiXiangKS22',
        'ZhiXiangKS',
        'ShuangJiKuaiShou',
        'TuSiKuaiShou01',
        'TouFang',
        'ZhaoHui',
        'Beta',
    ];
}
