<?php

namespace constant;

class RouterUrlConstant
{
    /*
     * 路由
     * */
    const URL_ALL_登录页面 = '/admin/loginIndex';
    const URL_ALL_登录操作 = '/admin/login';
    const URL_ALL_首页 = '/admin/index';
    const URL_ALL_控制台 = '/admin/indexConsole';
    const URL_ALL_退出登录 = '/admin/loginOut';
    const URL_ALL_管理员列表 = '/admin/adminUserLists';
    const URL_ALL_管理员添加 = '/admin/addAdminUser';
    const URL_ALL_管理员编辑 = '/admin/editAdminUserInfo';
    const URL_ALL_管理员删除 = '/admin/delAdminUser';
    const URL_ALL_角色列表 = '/admin/getRoleLists';
    const URL_ALL_角色添加 = '/admin/addRole';
    const URL_ALL_角色删除 = '/admin/delRole';
    const URL_ALL_角色权限分配 = '/admin/editRoleToMenu';
    const URL_ALL_角色编辑 = '/admin/editRole';
    const URL_ALL_节点列表 = '/admin/getMenuLists';
    const URL_ALL_节点添加 = '/admin/addMenuItems';
    const URL_ALL_节点编辑 = '/admin/editMenuItems';
    const URL_ALL_节点删除 = '/admin/delMenuItems';
    const URL_ALL_动态列表 = '/admin/getForumList';
    const URL_ALL_动态删除 = '/admin/delForum';
    const URL_ALL_动态评论列表 = '/admin/replyList';
    const URL_ALL_动态评论删除 = '/admin/delReply';
    const URL_ALL_动态审核列表 = '/admin/getForumAuditList';
    const URL_ALL_动态审核通过 = '/admin/forumAuditYes';
    const URL_ALL_动态审核拒绝 = '/admin/forumAuditNo';
    const URL_ALL_个人信息历史动态 = '/admin/getForumListByWhere';
    const URL_ALL_会员特权列表 = '/admin/vipPrivilege';
    const URL_ALL_会员特权添加 = '/admin/addPrivilege';
    const URL_ALL_会员特权图片上传 = '/admin/addPrivilegePicture';
    const URL_ALL_礼物列表 = '/admin/giftList';
    const URL_ALL_礼物添加 = '/admin/addGift';
    const URL_ALL_礼物修改 = '/admin/exitGift';
    const URL_ALL_礼物缓存修改 = '/admin/clearCache';
    const URL_ALL_礼物图片上传 = '/admin/ossFile';
    const URL_ALL_银箱子奖次礼物列表 = '/admin/caseYinList';
    const URL_ALL_银箱子添加指定用户绑定指定礼物 = '/admin/addYinGiftUserAssign';
    const URL_ALL_银箱子指定用户绑定指定礼物列表 = '/admin/getYinUserToGiftLists';
    const URL_ALL_银箱子取消指定用户绑定指定礼物 = '/admin/delYinUserToGiftAssign';
    const URL_ALL_金箱子奖次礼物列表 = '/admin/caseJinList';
    const URL_ALL_金箱子添加指定用户绑定指定礼物 = '/admin/addJinGiftUserAssign';
    const URL_ALL_金箱子指定用户绑定指定礼物列表 = '/admin/getJinUserToGiftLists';
    const URL_ALL_金箱子取消指定用户绑定指定礼物 = '/admin/delJinUserToGiftAssign';
    const URL_ALL_箱子指定中奖后接口 = '/admin/caseObtain';
    const URL_ALL_房间列表 = '/admin/roomList';
    const URL_ALL_配置砸蛋飘屏值 = '/admin/editroommsg';
    const URL_ALL_查询砸蛋飘屏值 = '/admin/getroommsg';
    const URL_ALL_配置砸蛋公屏值 = '/admin/editsaymsg';
    const URL_ALL_查询砸蛋公屏值 = '/admin/getsaymsg';
    const URL_ALL_配置砸蛋获得礼物 = '/admin/editegggift';
    const URL_ALL_查询砸蛋获得礼物 = '/admin/getegggift';
    const URL_ALL_房间编辑 = '/admin/roomEdit';
    const URL_ALL_房间类型列表 = '/admin/typeList';
    const URL_ALL_房间类型修改 = '/admin/exitRoomType';
    const URL_ALL_手动热度值列表 = '/admin/vsitorExternnumberLists';
    const URL_ALL_手动热度值添加 = '/admin/addRoomVisitorExternnumber';
    const URL_ALL_手动热度值编辑 = '/admin/editRoomVisitorExternnumber';
    const URL_ALL_手动热度值删除 = '/admin/delRoomVisitorExternnumber';
    const URL_ALL_广告列表 = '/admin/bannerList';
    const URL_ALL_广告添加 = '/admin/bannerAdd';
    const URL_ALL_广告编辑 = '/admin/bannerEdit';
    const URL_ALL_广告缓存清除 = '/admin/bannerClear';
    const URL_ALL_工会列表 = '/admin/guildList';
    const URL_ALL_工会添加 = '/admin/addGuilds';
    const URL_ALL_工会修改 = '/admin/guildEdit';
    const URL_ALL_工会成员列表 = '/admin/guildMember';
    const URL_ALL_工会成员添加 = '/admin/insertMember';
    const URL_ALL_工会成员修改 = '/admin/exitMember';
    const URL_ALL_工会成员删除 = '/admin/delGuildMember';
    const URL_ALL_防黑产列表 = '/admin/getUserScore';
    const URL_ALL_用户列表 = '/admin/memberList';
    const URL_ALL_用户详情 = '/admin/memberItem';
    const URL_ALL_用户靓号修改 = '/admin/editMemberPretty';
    const URL_ALL_用户昵称修改 = '/admin/editMemberNickname';
    const URL_ALL_用户用户名修改 = '/admin/editMemberUsername';
    const URL_ALL_用户解封 = '/admin/memberBlacks';
    const URL_ALL_用户封禁 = '/admin/memberUnsealings';
    const URL_ALL_用户收礼记录 = '/admin/getCoinDetailReceivingList';
    const URL_ALL_用户送礼记录 = '/admin/getCoinDetailGivingList';
    const URL_ALL_用户管理后台充值列表 = '/admin/getMemberMoneyDouList';
    const URL_ALL_用户管理后台充值添加 = '/admin/addMemberMoneyDou';
    const URL_ALL_用户客户端充值列表 = '/admin/getChargeDetailList';
    const URL_ALL_用户管理后台钻石添加 = '/admin/addMemberMoneyDiamondOne';
    const URL_ALL_用户管理后台钻石减少 = '/admin/addMemberMoneyDiamondTwo';
    const URL_ALL_用户管理后台钻石添加列表 = '/admin/getMemberMoneyDiamondOneList';
    const URL_ALL_用户管理后台钻石减少列表 = '/admin/getMemberMoneyDiamondTwoList';
    const URL_ALL_举报用户列表 = '/admin/complaintsList';
    const URL_ALL_标签列表 = '/admin/labelList';
    const URL_ALL_标签添加 = '/admin/addLabel';
    const URL_ALL_标签修改上下架 = '/admin/exitLabel';
    const URL_ALL_话题列表 = '/admin/topicList';
    const URL_ALL_话题添加 = '/admin/addTopic';
    const URL_ALL_话题标签修改 = '/admin/exitTopicTag';
    const URL_ALL_话题序号修改 = '/admin/exitTopicNum';
    const URL_ALL_话题上下架修改 = '/admin/exitTopicStatus';
    const URL_ALL_话题是否热门修改 = '/admin/exitTopicHot';
    const URL_ALL_公告列表 = '/admin/noticeList';
    const URL_ALL_公告已发布列表 = '/admin/publishedList';
    const URL_ALL_公告待发布列表 = '/admin/unpublishedList';
    const URL_ALL_公告已删除列表 = '/admin/deletedList';
    const URL_ALL_公告详情 = '/admin/noticeListOne';
    const URL_ALL_公告定时添加 = '/admin/addNotice';
    const URL_ALL_公告立即添加 = '/admin/nowAddNotice';
    const URL_ALL_公告保存 = '/admin/saveNotice';
    const URL_ALL_公告修改 = '/admin/exitNotice';
    const URL_ALL_公告删除 = '/admin/delNotice';
    const URL_ALL_公告恢复 = '/admin/recoverNotice';
    const URL_ALL_日志列表 = '/admin/getAdminLogsList';
    const URL_ALL_外包礼物兑奖管理员列表 = '/admin/subcontractingGiftAdminList';
    const URL_ALL_外包礼物兑奖管理员添加 = '/admin/addSubcontractingGiftAdmin';
    const URL_ALL_外包礼物兑奖管理员删除 = '/admin/delSubcontractingGiftAdmin';
    const URL_ALL_外包礼物兑奖管理员详情 = '/admin/subcontractingGiftAdminItem';
    const URL_ALL_定位测试 = '/admin/mapIndex';
    const URL_ALL_图片上传 = '/admin/uploadIndex';
    const URL_ALL_Banner图片修改 = '/admin/exitBannerImg';
    const URL_ALL_监控模式列表 = '/admin/monitoringList';
    const URL_ALL_修改监控模式 = '/admin/exitMonitoring';
    const URL_ALL_监控模式拒绝修改 = '/admin/noLock';
    const URL_ALL_活动列表 = '/admin/activeList';
    const URL_ALL_活动添加 = '/admin/addActive';
    const URL_ALL_提现列表 = '/admin/withdrawalList';
    const URL_ALL_公会钻石充值 = '/admin/ghBeanList';
    const URL_ALL_同意放款 = '/admin/agreeMake';
    const URL_ALL_拒绝放款 = '/admin/refuseMake';
    const URL_ALL_房间渠道关联修改 = '/admin/exitRoomChannel';
    const URL_ALL_Banner渠道关联修改 = '/admin/exitBannerChannel';
    const URL_ALL_装备列表 = '/admin/equipList';
    const URL_ALL_添加装备 = '/admin/equipAdd';
    const URL_ALL_修改装备 = '/admin/equipExid';
    const URL_ALL_装备详情 = '/admin/equipDetails';
    const URL_ALL_修改装备配置 = '/admin/equipExidProp';
    const URL_ALL_添加装备配置 = '/admin/equipAddProp';
    const URL_ALL_用户装备列表 = '/admin/userPackList';
    const URL_ALL_用户装备删除 = '/admin/userPackDel';
    const URL_ALL_用户装备佩戴 = '/admin/userPackAdorn';
    const URL_ALL_用户装备赠送列表 = '/admin/userPackGiveList';
    const URL_ALL_用户装备赠送 = '/admin/userPackGive';
    const URL_ALL_活动详情 = '/admin/activeItems';
    const URL_ALL_活动编辑 = '/admin/exitActive';
    const URL_ALL_活动开始 = '/admin/activeStart';
    const URL_ALL_活动结束 = '/admin/activeStop';
    const URL_ALL_数据列表 = '/admin/dataManagementIndex';
    const URL_ALL_用户每日明细查看 = '/admin/selectUserDetail';
    const URL_ALL_用户每日苹果支付明细查看 = '/admin/selectUserIos';
    const URL_ALL_用户每日微信支付明细查看 = '/admin/selectUserWechat';
    const URL_ALL_用户每日支付宝明细查看 = '/admin/selectUserAli';
    const URL_ALL_用户每日钻石转M豆明细查看 = '/admin/selectUserModes';
    const URL_ALL_用户每日获得礼物明细查看 = '/admin/selectUserGift';
    const URL_ALL_用户每日箱子明细查看 = '/admin/selectUserBox';
    const URL_ALL_用户每日猜拳明细查看 = '/admin/selectUserfinger';
    const URL_ALL_用户每日背包礼物明细查看 = '/admin/selectUserBagGift';
    const URL_ALL_用户每日购买礼物明细查看 = '/admin/selectUserPayGift';
    const URL_ALL_买银箱子钥匙明细查看 = '/admin/selectBuyYin';
    const URL_ALL_买金箱子钥匙明细查看 = '/admin/selectBuyJin';
    const URL_ALL_用银箱子钥匙明细查看 = '/admin/selectUseYin';
    const URL_ALL_用金箱子钥匙明细查看 = '/admin/selectUseJin';
    const URL_ALL_背包礼物发起猜拳明细查看 = '/admin/selectBagStart';
    const URL_ALL_充值礼物发起猜拳明细查看 = '/admin/selectPayStart';
    const URL_ALL_背包礼物应战猜拳明细查看 = '/admin/selectBagFight';
    const URL_ALL_充值礼物应战猜拳明细查看 = '/admin/selectPayFight';
    const URL_ALL_房间统计列表 = '/admin/roomdetail';
    const URL_ALL_房间用户统计列表 = '/admin/roomdmember';
    const URL_ALL_房间用户详情列表 = '/admin/roomdmemberdetail';
    const URL_ALL_渠道数据列表 = '/admin/channelindex';
    const URL_ALL_公会房间列表 = '/admin/guildroomlist';
    const URL_ALL_公会房间列表统计 = '/admin/guildroomdetail';
    const URL_ALL_房间消费列表 = '/admin/roomcoinlist';
    const URL_ALL_房间用户消费详情列表 = '/admin/roomcoindes';
    const URL_ALL_用户简介修改 = '/admin/editMemberIntro';
    const URL_ALL_用户头像修改 = '/admin/avatarOssFile';
    const URL_ALL_用户头像框修改 = '/admin/prettyavatarOssFile';
    const URL_ALL_房间信息修改 = '/admin/editRoom';
    const URL_ALL_推荐房间列表 = '/admin/roomRecommend';
    const URL_ALL_配置推荐房间 = '/admin/roomRecommendAdd';
    const URL_ALL_取消房间推荐 = '/admin/roomRecommendDel';
    const URL_ALL_房间超级管理员列表 = '/admin/ysuserList';
    const URL_ALL_配置房间超管 = '/admin/addYsUser';
    const URL_ALL_取消房间超管 = '/admin/delYsUser';
    const URL_ALL_编辑背景图 = '/admin/roomOssFile';
    const URL_ALL_配置公会房间 = '/admin/addGuidRoom';
    const URL_ALL_取消公会房间 = '/admin/delGuidRoom';
    const URL_ALL_编辑公会信息 = '/admin/exitGuild';
    const URL_ALL_意见反馈列表 = '/admin/feedbackList';
    const URL_ALL_充值记录 = '/admin/rechargelist';
    const URL_ALL_数据详情 = '/admin/retention';
    const URL_ALL_渠道数据详情 = '/admin/channelRetention';
    const URL_ALL_数据新增详情 = '/admin/userbiDetail';
    const URL_ALL_更换头像框地址修改 = '/admin/editPrettyAvatar';
    const URL_ALL_管理员操作用户钱包明细 = '/admin/usermoneylist';
    const URL_ALL_启动广告列表 = '/admin/advertList';
    const URL_ALL_启动广告添加 = '/admin/addAdvert';
    const URL_ALL_启动广告修改 = '/admin/editAdvert';
    const URL_ALL_启动广告图片修改 = '/admin/editAdvertImg';
    const URL_ALL_封禁用户列表 = '/admin/blackList';
    const URL_ALL_推广数据列表 = '/admin/doappList';
    const URL_ALL_周星数据列表 = '/admin/giftstart';
    const URL_ALL_周星数据添加 = '/admin/addGiftStart';
    const URL_ALL_周星数据修改 = '/admin/exitGiftStart';
    const URL_ALL_周星图标数据 = '/admin/ossFileStart';
    const URL_ALL_用户消费明细列表 = '/admin/getConsumeList';
    const URL_ALL_用户登录记录列表 = '/admin/getLoginList';
    const URL_ALL_用户续费数据列表 = '/admin/ratePayList';
    const URL_ALL_用户实名认证列表 = '/admin/userCardList';
    const URL_ALL_用户送礼明细列表 = '/admin/userCoin';
    const URL_ALL_账本数据列表 = '/admin/bill';
    const URL_ALL_账本明细列表 = '/admin/billDetail';
    const URL_ALL_音乐列表 = '/admin/musicList';
    const URL_ALL_音乐数据修改 = '/admin/musicStatus';
    const URL_ALL_音乐审核通过 = '/admin/musicYes';
    const URL_ALL_音乐审核拒绝 = '/admin/musicNo';
    const URL_ALL_派对房间列表 = '/admin/partyRoomLists';
    const URL_ALL_用户收礼明细列表 = '/admin/userGetCoin';
    const URL_ALL_房间背景图 = '/admin/BackgroundImageOfType';
    const URL_ALL_更改房间背景图 = '/admin/editRoomImageByType';
    const URL_ALL_删除房间背景图 = '/admin/delRoomImageByType';
    const URL_ALL_添加房间背景图 = '/admin/addRoomImageByType';
    const URL_ALL_装扮列表 = '/admin/getAttireList';
    const URL_ALL_装扮添加 = '/admin/addAttire';
    const URL_ALL_加入派对 = '/admin/addRoomParty';
    const URL_ALL_装扮分类列表 = '/admin/getAttireTypeList';
    const URL_ALL_装扮分类添加 = '/admin/addAttireType';
    const URL_ALL_装扮分类 = '/admin/getAttireType';
    const URL_ALL_装扮切换上下架 = '/admin/statusAttire';
    const URL_ALL_装扮修改 = '/admin/attireUpdateStatus';
    const URL_ALL_装扮分类修改 = '/admin/updateAttireType';
    const URL_ALL_装扮分类上下架切换 = '/admin/updateAttireType';
    const URL_ALL_装扮上下架切换 = '/admin/statusAttire';
    const URL_ALL_房间背景选择列表 = '/admin/roomBackgroundChoice';
    const URL_ALL_装扮图片上传 = '/admin/ossAttireFile';
    const URL_ALL_房间背景修改 = '/admin/roomChoiceType';
    const URL_ALL_房间分类列表 = '/admin/roomTypeList';
    const URL_ALL_房间分类状态修改 = '/admin/editTypeStatus';
    const URL_ALL_分类显示状态修改 = '/admin/editTypeShow';
    const URL_ALL_渠道列表 = '/admin/channelList';
    const URL_ALL_获取邀请码 = '/admin/getInviteCode';
    const URL_ALL_获取下级渠道列表 = '/admin/getChannelOfId';
    const URL_ALL_更新渠道信息 = '/admin/editChannel';
    const URL_ALL_渠道新增统计 = '/admin/addCensus';
    const URL_ALL_归属查询 = '/admin/affiliation';
    const URL_ALL_消费统计 = '/admin/Statistics';
    const URL_ALL_用户消费明细 = '/admin/statement';
    const URL_ALL_每日充值用户列表 = '/admin/payUser';
    const URL_ALL_添加公会首页房间 = '/admin/addGuidRoomIndex';
    const URL_ALL_取消公会首页房间 = '/admin/delGuidRoomIndex';
    const URL_ALL_用户剩余豆 = '/admin/leftUser';
    const URL_ALL_充值人数 = '/admin/userPay';
    const URL_ALL_宝箱爆奖率 = '/admin/TheLottery';
    const URL_ALL_礼物明细 = '/admin/giftFine';
    const URL_ALL_金宝箱 = '/admin/TheLotterj';
    const URL_ALL_消费分析 = '/admin/StatAot';
    const URL_ALL_宝箱开奖记录 = '/admin/BoxGiftList';
    const URL_ALL_开箱明细 = '/admin/BoxList';
    const URL_ALL_线上渠道数据列表 = '/admin/channel';
    const URL_ALL_渠道详情列表 = '/admin/channellist2';
    const URL_ALL_红包规则列表 = '/admin/RedTherulesList';
    const URL_ALL_留存 = '/admin/leave';
    const URL_ALL_红包列表 = '/admin/RedPackets';
    const URL_ALL_红包详情列表 = '/admin/RedpacketsDetail';
    const URL_ALL_红包金额设置 = '/admin/AddRedCoin';
    const URL_ALL_任务添加 = '/admin/TaskAdd';
    const URL_ALL_任务修改 = '/admin/TaskSave';
    const URL_ALL_主播开播时长与流水 = '/admin/PremiereTimeAndStream';
    const URL_ALL_用户充值总金额 = '/admin/online';
    const URL_ALL_用户许愿石详情 = '/admin/UserStone';
    const URL_ALL_随机匹配房间 = '/admin/RandomlyMatchedRoom';
    const URL_ALL_添加随机匹配房间 = '/admin/AddRandomlyMatchedRoom';
    const URL_ALL_删除随机匹配房间 = '/admin/delRandomlyMatchedRoom';
    const URL_ALL_新手任务列表 = '/admin/ListNewTask';
    const URL_ALL_热云 = '/admin/ReYun';
    const URL_ALL_热云详情 = '/admin/ReYunlist';
    const URL_ALL_热云推广详情 = '/admin/SpreadName';
    const URL_ALL_新手任务更新 = '/admin/NewTaskSave';
    const URL_ALL_每日任务列表 = '/admin/ListDailyTask';
    const URL_ALL_每日任务更新 = '/admin/DailyTaskSave';
    const URL_ALL_签到任务列表 = '/admin/ListSignTask';
    const URL_ALL_签到任务更新 = '/admin/SignTaskSave';
    const URL_ALL_日常任务列表 = '/admin/ListOftenTasks';
    const URL_ALL_日常任务更新 = '/admin/OftenTasksSave';
    const URL_ALL_VIP订单 = '/admin/VipOrder';
    const URL_ALL_虚拟币流水 = '/admin/MOrder';
    const URL_ALL_用户手机号 = '/admin/memberCash';
    const URL_ALL_删除用户手机号 = '/admin/MemberCashDel';
    const URL_ALL_用户留存 = '/admin/UsersRetained';
    const URL_ALL_用户留存详情 = '/admin/UsersRetainedDetails';
    const URL_ALL_删除数据 = '/admin/delete';
    const URL_ALL_删除数据页 = '/admin/delshow';
    const URL_ALL_删除房间名 = '/admin/delRoomName';
    const URL_ALL_房间模式名称 = '/admin/roomModel';
    const URL_ALL_金币抽奖奖励金币 = '/admin/listGold';
    const URL_ALL_添加金币抽奖奖励金币 = '/admin/addlistGold';
    const URL_ALL_删除金币抽奖奖励金币 = '/admin/dellistGold';
    const URL_ALL_修改金币抽奖奖励金币 = '/admin/updlistGold';
    const URL_ALL_金币抽奖奖励装扮 = '/admin/listGoldAttire';
    const URL_ALL_添加金币抽奖奖励装扮 = '/admin/addlistGoldAttire';
    const URL_ALL_修改金币抽奖奖励装扮 = '/admin/updlistGoldAttire';
    const URL_ALL_删除金币抽奖奖励装扮 = '/admin/dellistGoldAttire';
    const URL_ALL_金币抽奖奖励礼物 = '/admin/listGoldGift';
    const URL_ALL_添加金币抽奖奖励礼物 = '/admin/addlistGoldGift';
    const URL_ALL_修改金币抽奖奖励礼物 = '/admin/updlistGoldGift';
    const URL_ALL_删除金币抽奖奖励礼物 = '/admin/dellistGoldGift';
    const URL_ALL_房间标签 = '/admin/roomModelName';
    const URL_ALL_获取房间分类 = '/admin/getRoomModel';
    const URL_ALL_添加房间标签 = '/admin/addRoomModelName';
    const URL_ALL_金币礼物 = '/admin/goldGiftList';
    const URL_ALL_添加金币礼物 = '/admin/addGoldGift';
    const URL_ALL_修改金币礼物 = '/admin/exitGoldGift';
    const URL_ALL_清除金币礼物缓存 = '/admin/clearGoldCache';
    const URL_ALL_添加金币礼物图片 = '/admin/ossGoldFile';
    const URL_ALL_金币装扮 = '/admin/attListGold';
    const URL_ALL_金币装扮分类 = '/admin/attTypeGold';
    const URL_ALL_添加金币装扮 = '/admin/addAttGold';
    const URL_ALL_金币装扮图片上传 = '/admin/ossAttFileGold';
    const URL_ALL_金币装扮上下架切换 = '/admin/statusAttGold';
    const URL_ALL_修改金币装扮 = '/admin/attUpdGold';
    const URL_ALL_金币抽奖列表 = '/admin/goldCoinBox';
    const URL_ALL_礼物盒子展示 = '/admin/giftBox';
    const URL_ALL_礼物盒子添加 = '/admin/addGiftBox';
    const URL_ALL_礼物盒子删除 = '/admin/delGiftBox';
    const URL_ALL_装扮图片添加 = '/admin/attOssFile';
    const URL_ALL_礼物盒子清除缓存 = '/admin/clearCacheGiftBox';
    const URL_ALL_删除监控模式 = '/admin/delMonitoring';
    const URL_ALL_添加金币记录 = '/admin/getMemberGoldList';
    const URL_ALL_增减金币 = '/admin/addMemberGold';
    const URL_ALL_戳一戳配词列表 = '/admin/pokeWordsList';
    const URL_ALL_戳一戳配词添加 = '/admin/addPokeWords';
    const URL_ALL_戳一戳配词删除 = '/admin/delPokeWords';
    const URL_ALL_戳一戳清除缓存 = '/admin/clearCachePokeWords';
    const URL_ALL_打招呼消息列表 = '/admin/greetMessageList';
    const URL_ALL_打招呼消息添加 = '/admin/addGreetMessage';
    const URL_ALL_打招呼消息删除 = '/admin/delGreetMessage';
    const URL_ALL_打招呼消息清除缓存 = '/admin/clearCacheGreetMessage';
    const URL_ALL_添加房间分类图标 = '/admin/ossRoomType';
    const URL_ALL_添加房间分类 = '/admin/addRoomType';
    const URL_ALL_删除房间分类 = '/admin/delRoomType';
    const URL_ALL_添加顶级房间分类 = '/admin/addRoomTypeFather';
    const URL_ALL_表情包列表 = '/admin/listEmoticon';
    const URL_ALL_随机头像列表 = '/admin/cpRecommendImageList';
    const URL_ALL_随机头像添加 = '/admin/addcpRecommendImage';
    const URL_ALL_随机头像删除 = '/admin/delcpRecommendImage';
    const URL_ALL_随机头像清除缓存 = '/admin/clearCacheCpRecommendImage';
    const URL_ALL_表情添加 = '/admin/addEmoticon';
    const URL_ALL_表情删除 = '/admin/delEmoticon';
    const URL_ALL_表情编辑 = '/admin/saveEmoticon';
    const URL_ALL_表情缓存清除 = '/admin/clearGoldEmoti';
    const URL_ALL_修改数据 = '/admin/dataSave';
    const URL_ALL_修改数据展示 = '/admin/dataSaveShow';
    const URL_ALL_删除渠道管理员 = '/admin/delChannel';
    const URL_ALL_三级渠道列表 = '/admin/threeChannel';
    const URL_ALL_房间内首冲曝光点击 = '/admin/ChannelPoints';
    const URL_ALL_表情图修改 = '/admin/ossEmoticonFile';
    const URL_ALL_敏感词展示 = '/admin/bannedList';
    const URL_ALL_敏感词添加 = '/admin/addBanned';
    const URL_ALL_敏感词删除 = '/admin/delBanned';
    const URL_ALL_敏感词清除缓存 = '/admin/clearBanned';
    const URL_ALL_聊天记录 = '/admin/messageList';
    const URL_ALL_聊天详情 = '/admin/messageData';
    const URL_ALL_获取渠道ID = '/admin/level';
    const URL_ALL_渠道用户分组 = '/admin/group';
    const URL_ALL_用户礼物列表 = '/admin/userGift';
    const URL_ALL_三级渠道 = '/admin/Three';
    const URL_ALL_飞行棋 = '/admin/gameList';
    const URL_ALL_飞行棋奖池 = '/admin/gameJson';
    const URL_ALL_飞行棋奖池编辑 = '/admin/saveGame';
    const URL_ALL_飞行棋奖池清除缓存 = '/admin/clearGame';
    const URL_ALL_矿石礼物 = '/admin/Exchange';
    const URL_ALL_矿石礼物编辑 = '/admin/saveExchange';
    const URL_ALL_奖池比例 = '/admin/gameProportion';
    const URL_ALL_奖池比例编辑 = '/admin/saveProportion';
    const URL_ALL_点击隐藏显示青少年模式 = '/admin/Teenagers';
    const URL_ALL_点击分类 = '/admin/Classification';
    const URL_ALL_cp和游戏 = '/admin/CpThegame';
    const URL_ALL_点击匹配 = '/admin/Matching';
    const URL_ALL_点击动态 = '/admin/Dynamic';
    const URL_ALL_首页去找他 = '/admin/HomePageLooking';
    const URL_ALL_首页大厅 = '/admin/HomePageThehall';
    const URL_ALL_打招呼 = '/admin/SayHhello';
    const URL_ALL_戳一下 = '/admin/PokeThe';
    const URL_ALL_发布动态 = '/admin/ReleaseTheDynamic';
    const URL_ALL_添加矿石礼物位置 = '/admin/addExchange';
    const URL_ALL_移除矿石礼物位置 = '/admin/delExchange';
    const URL_ALL_飞行棋奖励列表 = '/admin/gameLog';
    const URL_ALL_飞行棋兑换记录 = '/admin/GameExchangeLog';
    const URL_ALL_飞行棋房间赠礼 = '/admin/RoomGame';
    const URL_ALL_幸运盒子爆率 = '/admin/TheLottery';
    const URL_ALL_添加虚拟用户 = '/admin/addUser';
    const URL_ALL_飞行棋图片 = '/admin/GameImage';
    const URL_ALL_用户邀请码添加 = '/admin/addUserCode';
    const URL_ALL_用户流失 = '/admin/memberLoss';
    const URL_ALL_修改用户礼物数量 = '/admin/SaveUserGift';
    const URL_ALL_幸运盒子详情 = '/admin/luckyBoxList';
    const URL_ALL_用户背包礼物添加 = '/admin/addPackGift';
    const URL_ALL_新实名认证列表 = '/admin/newUserCardList';
    const URL_ALL_用户体力 = '/admin/UserPhysicalStrength';
    const URL_ALL_添加用户体力 = '/admin/addUserPhysicalStrength';
    const URL_ALL_三封列表 = '/admin/UserBlack';
    const URL_ALL_三封编辑 = '/admin/SaveUserBlack';
    const URL_ALL_游戏列表 = '/admin/GiftGame';
    const URL_ALL_游戏开关 = '/admin/GiftGameStatus';
    const URL_ALL_用户注销列表 = '/admin/cancelUserStatus';
    const URL_ALL_用户注销操作 = '/admin/cancelUserStatusSave';
    const URL_ALL_用户注销取消操作 = '/admin/cancelUserStatusCancel';
    const URL_ALL_广告自动化时间 = '/admin/bannerOpen';
    const URL_ALL_爵位列表 = '/admin/dukeList';
    const URL_ALL_爵位添加 = '/admin/dukeAdd';
    const URL_ALL_爵位详情 = '/admin/dukeDetails';
    const URL_ALL_爵位编辑 = '/admin/dukeSave';
    const URL_ALL_爵位用户 = '/admin/dukeMember';
    const URL_ALL_爵位用户添加 = '/admin/dukeAdd';
    const URL_ALL_后台装备管理 = '/admin/GivePackList';
    const URL_ALL_sql展示 = '/admin/sqlShwo';
    const URL_ALL_sql执行 = '/admin/sqlQuery';
    const URL_ALL_房间魅力值榜单 = '/admin/roomConsumption';
    const URL_ALL_房间财富值榜单 = '/admin/roomConsumptionRich';
    const URL_ALL_房间魅力值周榜单 = '/admin/roomConsumptionWeekLike';
    const URL_ALL_房间财富值周榜单 = '/admin/roomConsumptionWeekRich';
    const URL_ALL_指定封禁功能列表 = '/admin/deviceIpList';
    const URL_ALL_指定封禁功能添加 = '/admin/deviceIpAdd';
    const URL_ALL_送礼飘屏 = '/admin/sendGiftNum';
    const URL_ALL_修改送礼飘屏 = '/admin/sendGiftNumSave';
    const URL_ALL_新三封编辑 = '/admin/deviceIpSave';
    const URL_ALL_用户登录记录 = '/admin/loginDetail';
    const URL_ALL_添加房间靓号 = '/admin/addRoomPretty';
    const URL_ALL_设置房间默认背景图 = '/admin/photoWallStart';
    const URL_ALL_爵位清除缓存 = '/admin/dukeRedis';
    const URL_ALL_设备黑名单 = '/admin/deviceDeviceidList';
    const URL_ALL_身份证黑名单 = '/admin/deviceIdcardList';
    const URL_ALL_房間分類排序 = '/admin/saveRoomModeSor';
    const URL_ALL_周星财富列表 = '/admin/giftWealth';
    const URL_ALL_添加财富周星 = '/admin/addGiftWealth';
    const URL_ALL_编辑财富周星 = '/admin/exitGiftWealth';
    const URL_ALL_月魅力列表 = '/admin/giftMonth';
    const URL_ALL_添加月魅力 = '/admin/addGiftMonth';
    const URL_ALL_编辑月魅力 = '/admin/exitGiftMonth';
    const URL_ALL_商品配置 = '/admin/goodsConf';
    const URL_ALL_商品编辑 = '/admin/goodsConfSave';
    const URL_ALL_商品添加 = '/admin/goodsAdd';
    const URL_ALL_商品详情 = '/admin/goodsConfDetails';
    const URL_ALL_商品详情修改 = '/admin/goodsDetailsSave';
    const URL_ALL_商城列表 = '/admin/mallConf';
    const URL_ALL_商城列表添加 = '/admin/mallConfAdd';
    const URL_ALL_商城配置第一层 = '/admin/mallconfDetails';
    const URL_ALL_商城配置第二层 = '/admin/mallconfAreas';
    const URL_ALL_商城添加商品 = '/admin/mallAddGoods';
    const URL_ALL_删除商城商品 = '/admin/mallAddGoods';
    const URL_ALL_礼物配置 = '/admin/giftConf';
    const URL_ALL_礼物配置添加 = '/admin/giftConfAdd';
    const URL_ALL_礼物配置删除 = '/admin/giftConfDel';
    const URL_ALL_礼物配置保存 = '/admin/giftConfSave';
    const URL_ALL_礼物配置文件 = '/admin/giftConfImg';
    const URL_ALL_礼物面板 = '/admin/giftPanels';
    const URL_ALL_礼物面板详情 = '/admin/giftPanelsDetails';
    const URL_ALL_礼物商城分类添加 = '/admin/giftClassificationAdd';
    const URL_ALL_礼物面板添加 = '/admin/giftPanelsAdd';
    const URL_ALL_代充用户列表 = '/admin/daichong';
    const URL_ALL_添加代充用户 = '/admin/daichongAdd';
    const URL_ALL_删除代充用户 = '/admin/daichongStatus';
    const URL_ALL_删除面板礼物 = '/admin/giftPanelsDel';
    const URL_ALL_礼物商城初始化 = '/admin/giftPanelsTheFirst';
    const URL_ALL_礼物商城 = '/admin/giftWall';
    const URL_ALL_礼物商城详情 = '/admin/giftWallDetails';
    const URL_ALL_添加礼物面板礼物 = '/admin/giftWallAdd';
    const URL_ALL_删除礼物面板礼物 = '/admin/giftWallDel';
    const URL_ALL_装扮配置 = '/admin/propConf';
    const URL_ALL_添加装扮配置 = '/admin/propConfAdd';
    const URL_ALL_删除装扮配置 = '/admin/propConfDel';
    const URL_ALL_编辑装扮配置 = '/admin/propConfSave';
    const URL_ALL_表情包配置 = '/admin/emoticonConf';
    const URL_ALL_表情包配置添加 = '/admin/emoticonConfAdd';
    const URL_ALL_表情包配置编辑 = '/admin/emoticonConfSave';
    const URL_ALL_表情包配置删除 = '/admin/emoticonConfDel';
    const URL_ALL_表情包面板 = '/admin/emoticonPanelsConf';
    const URL_ALL_表情包面板详情 = '/admin/emoticonPanelsConfDetails';
    const URL_ALL_添加表情包面板 = '/admin/emoticonPanelsConfAdd';
    const URL_ALL_删除表情包面板 = '/admin/emoticonPanelsConfDel';
    const URL_ALL_红包活动 = '/admin/activityRed';
    const URL_ALL_添加红包活动 = '/admin/addActivityRed';
    const URL_ALL_三人夺宝奖池 = '/admin/treasurePool';
    const URL_ALL_三人夺宝奖池礼物 = '/admin/treasurePoolDetails';
    const URL_ALL_三人夺宝奖池添加礼物 = '/admin/treasurePoolDetailsAdd';
    const URL_ALL_三人夺宝奖池删除礼物 = '/admin/treasurePoolDetailsDel';
    const URL_ALL_红包活动礼物 = '/admin/activityRedDetails';
    const URL_ALL_红包活动礼物添加 = '/admin/actRedGiftAdd';
    const URL_ALL_红包活动礼物删除 = '/admin/actRedGiftDel';
    const URL_ALL_渠道详情 = '/admin/channelDetails';
    const URL_ALL_渠道付费用户 = '/admin/channelPay';
    const URL_ALL_工会充值用户 = '/admin/userPayBeancredit';
    const URL_ALL_礼物墙开关展示 = '/admin/giftWallStatus';
    const URL_ALL_礼物墙开关修改 = '/admin/giftWallStatusSave';
    const URL_ALL_三人夺宝产出 = '/admin/treasurePoolList';
    const URL_ALL_流失用户 = '/admin/iossUser';
    const URL_ALL_缓存配置 = '/admin/redisConfig';
    const URL_ALL_瓜分番茄豆 = '/admin/shavePoints';
    const URL_ALL_瓜分番茄豆编辑 = '/admin/shavePointsSave';
    const URL_ALL_商城配置第二层添加 = '/admin/mallconfDetailsAdd';
    const URL_ALL_爵位配置 = '/admin/dukeConfig';
    const URL_ALL_爵位配置添加 = '/admin/dukeConfigAdd';
    const URL_ALL_爵位详情配置 = '/admin/dukeDetails';
    const URL_ALL_每日任务配置 = '/admin/weekcheckin';
    const URL_ALL_会员配置 = '/admin/vipConf';
    const URL_ALL_淘金配置 = '/admin/taojinConf';
    const URL_ALL_淘金数据列表 = '/admin/taojinActivityList';
    const URL_ALL_淘金详情 = '/admin/taojinContent';
    const URL_ALL_新手任务配置 = '/admin/newerConf';
    const URL_ALL_金币抽奖配置 = '/admin/lotteryConf';
    const URL_ALL_等级配置 = '/admin/levelConf';
    const URL_ALL_活跃度奖励配置 = '/admin/activeboxConf';
    const URL_ALL_活跃度宝箱奖励详情配置 = '/admin/activeboxdetails';
    const URL_ALL_宝箱配置 = '/admin/boxConf';
    const URL_ALL_宝箱配置保存 = '/admin/boxConfSave';
    const URL_ALL_充值配置 = '/admin/chargeConf';
    const URL_ALL_充值面板配置 = '/admin/chargemallConf';
    const URL_ALL_登录任务配置 = '/admin/dailyConf';
    const URL_ALL_跑量列表 = '/admin/PaoLiangList';
    const URL_ALL_跑量添加 = '/admin/AddPaoLiang';
    const URL_ALL_跑量导出 = '/admin/PaoLiangDaoChu';
    const URL_ALL_跑量充值详情 = '/admin/PaoLiangChongzhi';
    const URL_ALL_跑量删除 = '/admin/DelPaoLiang';
    const URL_ALL_跑量编辑 = '/admin/PaoLiangSave';
    const URL_ALL_跑量用户id导出 = '/admin/PaoLiangXinzeng';
    const URL_ALL_mua新厅推荐 = '/admin/muaNewRoomRecommend';
    const URL_ALL_mua新厅推荐保存 = '/admin/muaNewRoomRecommendSave';
    const URL_ALL_mua房间金刚位 = '/admin/muaRoomKingKong';
    const URL_ALL_配置展示页面 = '/admin/configShow';
    const URL_ALL_重构初始化 = '/admin/ChuShiHua';
    const URL_ALL_跑量留存导出 = '/admin/PaoLiangLiuCun';
    const URL_ALL_跑量详情 = '/admin/xingzengxiangqing';
    const URL_ALL_跑量配置 = '/admin/zbRoomPromotionConf';
    const URL_ALL_添加跑量 = '/admin/zbRoomPromotionConfAdd';
    const URL_ALL_推广渠道列表 = '/admin/PromotionList';
    const URL_ALL_推广渠道新增 = '/admin/PromotionAdd';
    const URL_ALL_推广房间列表 = '/admin/PromotionRoomList';
    const URL_ALL_渠道新增推广房间 = '/admin/PromotionAddRoom';
    const URL_ALL_推广场次配置 = '/admin/PromotionTimesList';
    const URL_ALL_渠道新增推广场次 = '/admin/PromotionAddRoomTimes';
    const URL_ALL_用户回归活动 = '/admin/returnUserActivityConfig';
    const URL_ALL_用户回归活动编辑 = '/admin/returnSave';
    const URL_ALL_万千宠爱奖励配置 = '/admin/weeksCharmConf';
    const URL_ALL_周星活动 = '/admin/weeksActive';
    const URL_ALL_添加周星奖励 = '/admin/addWeeksConfig';
    const URL_ALL_编辑万千宠爱奖励 = '/admin/saveWeeksConfig';
    const URL_ALL_用户登录信息列表 = '/admin/loginUserInfo';
    const URL_ALL_君临天下奖励配置 = '/admin/weeksWealthConf';
    const URL_ALL_月榜奖励配置 = '/admin/weeksMonthConf';
    const URL_ALL_宝箱 = '/admin/getBoxConf';
    const URL_ALL_添加宝箱 = '/admin/addBox';
    const URL_ALL_宝箱奖池 = '/admin/boxPool';
    const URL_ALL_添加奖池 = '/admin/addBoxPool';
    const URL_ALL_编辑宝箱奖池 = '/admin/saveBoxPool';
    const URL_ALL_编辑奖池 = '/admin/savePool';
    const URL_ALL_宝箱爆率 = '/admin/BoxBurstRate';
    const URL_ALL_公屏和跑马灯 = '/admin/bag';
    const URL_ALL_保存公屏和跑马灯 = '/admin/savePublicScreen';
    const URL_ALL_砸蛋详情 = '/admin/BoxDetails';
    const URL_ALL_指定宝箱礼物 = '/admin/TheSpecifiedBoxGift';
    const URL_ALL_添加指定宝箱礼物 = '/admin/addTheSpecifiedBoxGift';
    const URL_ALL_取消指定宝箱礼物 = '/admin/cancelTheSpecifiedBoxGift';
    const URL_ALL_实时爆率 = '/admin/RealTimeRate';
    const URL_ALL_宝箱上线 = '/admin/clearCacheBoxConf';
    const URL_ALL_刷新宝箱奖池 = '/admin/refreshAllPool';
    const URL_ALL_获取奖池剩余 = '/admin/jackpotTheRemaining';
    const URL_ALL_指定转盘礼物 = '/admin/TheSpecifiedTurntableGift';
    const URL_ALL_添加指定转盘礼物 = '/admin/addTheSpecifiedTurntableGift';
    const URL_ALL_取消指定转盘礼物 = '/admin/cancelTheSpecifiedTurntableGift';
    const URL_ALL_转盘配置 = '/admin/getTurntableConf';
    const URL_ALL_添加转盘 = '/admin/addTurntable';
    const URL_ALL_编辑转盘 = '/admin/saveTurntable';
    const URL_ALL_转盘上线 = '/admin/clearCacheTurntableConf';
    const URL_ALL_获取转盘奖池礼物 = '/admin/getTurntablePoolGift';

    const URL_ALL_MAP = [
        self::URL_ALL_充值记录 => '充值记录',
        self::URL_ALL_房间消费列表 => '房间消费列表',
        self::URL_ALL_房间用户消费详情列表 => '房间用户消费详情列表',
        self::URL_ALL_登录页面 => '登录页面',
        self::URL_ALL_登录操作 => '登录操作',
        self::URL_ALL_首页 => '首页',
        self::URL_ALL_控制台 => '控制台',
        self::URL_ALL_退出登录 => '退出登录',
        self::URL_ALL_管理员列表 => '管理员列表',
        self::URL_ALL_管理员添加 => '管理员添加',
        self::URL_ALL_管理员编辑 => '管理员编辑',
        self::URL_ALL_管理员删除 => '管理员删除',
        self::URL_ALL_角色列表 => '角色列表',
        self::URL_ALL_角色添加 => '角色添加',
        self::URL_ALL_角色删除 => '角色删除',
        self::URL_ALL_角色权限分配 => '角色权限分配',
        self::URL_ALL_角色编辑 => '角色编辑',
        self::URL_ALL_节点列表 => '节点列表',
        self::URL_ALL_节点添加 => '节点添加',
        self::URL_ALL_节点编辑 => '节点编辑',
        self::URL_ALL_节点删除 => '节点删除',
        self::URL_ALL_动态列表 => '动态列表',
        self::URL_ALL_动态删除 => '动态删除',
        self::URL_ALL_动态评论列表 => '动态评论列表',
        self::URL_ALL_动态评论删除 => '动态评论删除',
        self::URL_ALL_动态审核列表 => '动态审核列表',
        self::URL_ALL_动态审核通过 => '动态审核通过',
        self::URL_ALL_动态审核拒绝 => '动态审核拒绝',
        self::URL_ALL_个人信息历史动态 => '个人信息历史动态',
        self::URL_ALL_会员特权列表 => '会员特权列表',
        self::URL_ALL_会员特权添加 => '会员特权添加',
        self::URL_ALL_会员特权图片上传 => '会员特权图片上传',
        self::URL_ALL_礼物列表 => '礼物列表',
        self::URL_ALL_礼物添加 => '礼物添加',
        self::URL_ALL_礼物修改 => '礼物修改',
        self::URL_ALL_礼物缓存修改 => '礼物缓存修改',
        self::URL_ALL_礼物图片上传 => '礼物图片上传',
        self::URL_ALL_银箱子奖次礼物列表 => '银箱子奖次礼物列表',
        self::URL_ALL_银箱子添加指定用户绑定指定礼物 => '银箱子添加指定用户绑定指定礼物',
        self::URL_ALL_银箱子指定用户绑定指定礼物列表 => '银箱子指定用户绑定指定礼物列表',
        self::URL_ALL_银箱子取消指定用户绑定指定礼物 => '银箱子取消指定用户绑定指定礼物',
        self::URL_ALL_金箱子奖次礼物列表 => '金箱子奖次礼物列表',
        self::URL_ALL_金箱子添加指定用户绑定指定礼物 => '金箱子添加指定用户绑定指定礼物',
        self::URL_ALL_金箱子指定用户绑定指定礼物列表 => '金箱子指定用户绑定指定礼物列表',
        self::URL_ALL_金箱子取消指定用户绑定指定礼物 => '金箱子取消指定用户绑定指定礼物',
        self::URL_ALL_箱子指定中奖后接口 => '箱子指定中奖后接口',
        self::URL_ALL_房间列表 => '房间列表',
        self::URL_ALL_配置砸蛋飘屏值 => '配置砸蛋飘屏值',
        self::URL_ALL_查询砸蛋飘屏值 => '查询砸蛋飘屏值',
        self::URL_ALL_配置砸蛋公屏值 => '配置砸蛋公屏值',
        self::URL_ALL_查询砸蛋公屏值 => '查询砸蛋公屏值',
        self::URL_ALL_配置砸蛋获得礼物 => '配置砸蛋获得礼物',
        self::URL_ALL_查询砸蛋获得礼物 => '查询砸蛋获得礼物',
        self::URL_ALL_房间编辑 => '房间编辑',
        self::URL_ALL_房间类型列表 => '房间类型列表',
        self::URL_ALL_房间类型修改 => '房间类型修改',
        self::URL_ALL_手动热度值列表 => '手动热度值列表',
        self::URL_ALL_手动热度值添加 => '手动热度值添加',
        self::URL_ALL_手动热度值编辑 => '手动热度值编辑',
        self::URL_ALL_手动热度值删除 => '手动热度值删除',
        self::URL_ALL_广告列表 => '广告列表',
        self::URL_ALL_广告添加 => '广告添加',
        self::URL_ALL_广告编辑 => '广告编辑',
        self::URL_ALL_广告缓存清除 => '广告缓存清除',
        self::URL_ALL_工会列表 => '工会列表',
        self::URL_ALL_工会添加 => '工会添加',
        self::URL_ALL_工会修改 => '工会修改',
        self::URL_ALL_工会成员列表 => '工会成员列表',
        self::URL_ALL_工会成员添加 => '工会成员添加',
        self::URL_ALL_工会成员修改 => '工会成员修改',
        self::URL_ALL_工会成员删除 => '工会成员删除',
        self::URL_ALL_用户列表 => '用户列表',
        self::URL_ALL_用户详情 => '用户详情',
        self::URL_ALL_用户靓号修改 => '用户靓号修改',
        self::URL_ALL_用户昵称修改 => '用户昵称修改',
        self::URL_ALL_用户用户名修改 => '用户用户名修改',
        self::URL_ALL_用户解封 => '用户解封',
        self::URL_ALL_用户封禁 => '用户封禁',
        self::URL_ALL_用户收礼记录 => '用户收礼记录',
        self::URL_ALL_用户送礼记录 => '用户送礼记录',
        self::URL_ALL_用户管理后台充值列表 => '用户管理后台充值列表',
        self::URL_ALL_用户管理后台充值添加 => '用户管理后台充值添加',
        self::URL_ALL_用户客户端充值列表 => '用户客户端充值列表',
        self::URL_ALL_用户管理后台钻石添加 => '用户管理后台钻石添加',
        self::URL_ALL_用户管理后台钻石减少 => '用户管理后台钻石减少',
        self::URL_ALL_用户管理后台钻石添加列表 => '用户管理后台钻石添加列表',
        self::URL_ALL_用户管理后台钻石减少列表 => '用户管理后台钻石减少列表',
        self::URL_ALL_举报用户列表 => '举报用户列表',
        self::URL_ALL_标签列表 => '标签列表',
        self::URL_ALL_标签添加 => '标签添加',
        self::URL_ALL_标签修改上下架 => '标签修改上下架',
        self::URL_ALL_话题列表 => '话题列表',
        self::URL_ALL_话题添加 => '话题添加',
        self::URL_ALL_话题标签修改 => '话题标签修改',
        self::URL_ALL_话题序号修改 => '话题序号修改',
        self::URL_ALL_话题上下架修改 => '话题上下架修改',
        self::URL_ALL_话题是否热门修改 => '话题是否热门修改',
        self::URL_ALL_公告列表 => '公告列表',
        self::URL_ALL_公告已发布列表 => '公告已发布列表',
        self::URL_ALL_公告待发布列表 => '公告待发布列表',
        self::URL_ALL_公告已删除列表 => '公告已删除列表',
        self::URL_ALL_公告详情 => '公告详情',
        self::URL_ALL_公告定时添加 => '公告定时添加',
        self::URL_ALL_公告立即添加 => '公告立即添加',
        self::URL_ALL_公告保存 => '公告保存',
        self::URL_ALL_公告修改 => '公告修改',
        self::URL_ALL_公告删除 => '公告删除',
        self::URL_ALL_公告恢复 => '公告恢复',
        self::URL_ALL_日志列表 => '日志列表',
        self::URL_ALL_外包礼物兑奖管理员列表 => '外包礼物兑奖管理员列表',
        self::URL_ALL_外包礼物兑奖管理员添加 => '外包礼物兑奖管理员添加',
        self::URL_ALL_外包礼物兑奖管理员删除 => '外包礼物兑奖管理员删除',
        self::URL_ALL_外包礼物兑奖管理员详情 => '外包礼物兑奖管理员详情',
        self::URL_ALL_定位测试 => '定位测试',
        self::URL_ALL_图片上传 => '图片上传',
        self::URL_ALL_Banner图片修改 => 'Banner图片修改',
        self::URL_ALL_监控模式列表 => '监控模式列表',
        self::URL_ALL_修改监控模式 => '修改监控模式',
        self::URL_ALL_监控模式拒绝修改 => '监控模式拒绝修改',
        self::URL_ALL_活动列表 => '活动列表',
        self::URL_ALL_活动添加 => '活动添加',
        self::URL_ALL_提现列表 => '提现列表',
        self::URL_ALL_公会钻石充值 => '公会钻石充值',
        self::URL_ALL_同意放款 => '同意放款',
        self::URL_ALL_拒绝放款 => '拒绝放款',
        self::URL_ALL_房间渠道关联修改 => '房间渠道关联修改',
        self::URL_ALL_Banner渠道关联修改 => 'Banner渠道关联修改',
        self::URL_ALL_装备列表 => '装备列表',
        self::URL_ALL_添加装备 => '添加装备',
        self::URL_ALL_修改装备 => '修改装备',
        self::URL_ALL_装备详情 => '装备详情',
        self::URL_ALL_修改装备配置 => '修改装备配置',
        self::URL_ALL_添加装备配置 => '添加装备配置',
        self::URL_ALL_用户装备列表 => '用户装备列表',
        self::URL_ALL_用户装备删除 => '用户装备删除',
        self::URL_ALL_用户装备佩戴 => '用户装备佩戴',
        self::URL_ALL_用户装备赠送列表 => '用户装备赠送列表',
        self::URL_ALL_用户装备赠送 => '用户装备赠送',
        self::URL_ALL_活动详情 => '活动详情',
        self::URL_ALL_活动编辑 => '活动编辑',
        self::URL_ALL_活动开始 => '活动开始',
        self::URL_ALL_活动结束 => '活动结束',
        self::URL_ALL_数据列表 => '数据列表',
        self::URL_ALL_用户每日明细查看 => '用户每日明细查看',
        self::URL_ALL_用户每日苹果支付明细查看 => '用户每日苹果支付明细查看',
        self::URL_ALL_用户每日微信支付明细查看 => '用户每日微信支付明细查看',
        self::URL_ALL_用户每日支付宝明细查看 => '用户每日支付宝明细查看',
        self::URL_ALL_用户每日钻石转M豆明细查看 => '用户每日钻石转M豆明细查看',
        self::URL_ALL_用户每日获得礼物明细查看 => '用户每日获得礼物明细查看',
        self::URL_ALL_用户每日箱子明细查看 => '用户每日箱子明细查看',
        self::URL_ALL_用户每日猜拳明细查看 => '用户每日猜拳明细查看',
        self::URL_ALL_用户每日背包礼物明细查看 => '用户每日背包礼物明细查看',
        self::URL_ALL_用户每日购买礼物明细查看 => '用户每日购买礼物明细查看',
        self::URL_ALL_买银箱子钥匙明细查看 => '买银箱子钥匙明细查看',
        self::URL_ALL_买金箱子钥匙明细查看 => '买金箱子钥匙明细查看',
        self::URL_ALL_用银箱子钥匙明细查看 => '用银箱子钥匙明细查看',
        self::URL_ALL_用金箱子钥匙明细查看 => '用金箱子钥匙明细查看',
        self::URL_ALL_背包礼物发起猜拳明细查看 => '背包礼物发起猜拳明细查看',
        self::URL_ALL_充值礼物发起猜拳明细查看 => '充值礼物发起猜拳明细查看',
        self::URL_ALL_背包礼物应战猜拳明细查看 => '背包礼物应战猜拳明细查看',
        self::URL_ALL_充值礼物应战猜拳明细查看 => '充值礼物应战猜拳明细查看',
        self::URL_ALL_房间统计列表 => '房间统计列表',
        self::URL_ALL_房间用户统计列表 => '房间用户统计列表',
        self::URL_ALL_房间用户详情列表 => '房间用户详情列表',
        self::URL_ALL_渠道数据列表 => '渠道数据列表',
        self::URL_ALL_公会房间列表 => '公会房间列表',
        self::URL_ALL_公会房间列表统计 => '公会房间列表统计',
        self::URL_ALL_用户简介修改 => '用户简介修改',
        self::URL_ALL_用户头像修改 => '_用户头像修改',
        self::URL_ALL_用户头像框修改 => '_用户头像框修改',
        self::URL_ALL_房间信息修改 => '房间信息修改',
        self::URL_ALL_推荐房间列表 => '推荐房间列表',
        self::URL_ALL_配置推荐房间 => '配置推荐房间',
        self::URL_ALL_取消房间推荐 => '取消房间推荐',
        self::URL_ALL_房间超级管理员列表 => '房间超级管理员列表',
        self::URL_ALL_配置房间超管 => '配置房间超管',
        self::URL_ALL_取消房间超管 => '取消房间超管',
        self::URL_ALL_编辑背景图 => '编辑背景图',
        self::URL_ALL_配置公会房间 => '_配置公会房间',
        self::URL_ALL_取消公会房间 => '取消公会房间',
        self::URL_ALL_编辑公会信息 => '编辑公会信息',
        self::URL_ALL_意见反馈列表 => '意见反馈列表',
        self::URL_ALL_数据详情 => '数据详情',
        self::URL_ALL_渠道数据详情 => '渠道数据详情',
        self::URL_ALL_数据新增详情 => '数据新增详情',
        self::URL_ALL_更换头像框地址修改 => '更换头像框地址修改',
        self::URL_ALL_管理员操作用户钱包明细 => '管理员操作用户钱包明细',
        self::URL_ALL_启动广告列表 => '启动广告列表',
        self::URL_ALL_启动广告添加 => '启动广告添加',
        self::URL_ALL_启动广告修改 => '启动广告修改',
        self::URL_ALL_启动广告图片修改 => '启动广告图片修改',
        self::URL_ALL_封禁用户列表 => '封禁用户列表',
        self::URL_ALL_推广数据列表 => '推广数据列表',
        self::URL_ALL_周星数据列表 => '周星数据列表',
        self::URL_ALL_周星数据添加 => '周星数据添加',
        self::URL_ALL_周星数据修改 => '周星数据修改',
        self::URL_ALL_周星图标数据 => '周星图标数据',
        self::URL_ALL_用户消费明细列表 => '用户消费明细列表',
        self::URL_ALL_用户登录记录列表 => '用户登录记录列表',
        self::URL_ALL_用户续费数据列表 => '用户续费数据列表',
        self::URL_ALL_用户实名认证列表 => '用户实名认证列表',
        self::URL_ALL_用户送礼明细列表 => '用户送礼明细列表',
        self::URL_ALL_账本数据列表 => '账本数据列表',
        self::URL_ALL_账本明细列表 => '账本明细列表',
        self::URL_ALL_音乐列表 => '音乐列表',
        self::URL_ALL_音乐数据修改 => '音乐数据修改',
        self::URL_ALL_音乐审核通过 => '音乐审核通过',
        self::URL_ALL_音乐审核拒绝 => '音乐审核拒绝',
        self::URL_ALL_派对房间列表 => '派对房间列表',
        self::URL_ALL_用户收礼明细列表 => '用户收礼明细列表',
        self::URL_ALL_房间背景图 => '房间背景图列表',
        self::URL_ALL_更改房间背景图 => '更改房间背景图',
        self::URL_ALL_删除房间背景图 => '删除房间背景图',
        self::URL_ALL_添加房间背景图 => '添加房间背景图',
        self::URL_ALL_装扮列表 => '装扮列表',
        self::URL_ALL_装扮添加 => '装扮添加',
        self::URL_ALL_加入派对 => '加入派对',
        self::URL_ALL_装扮分类列表 => '装扮分类列表',
        self::URL_ALL_装扮分类添加 => '装扮分类添加',
        self::URL_ALL_装扮分类 => '装扮分类',
        self::URL_ALL_装扮切换上下架 => '装扮切换上下架',
        self::URL_ALL_装扮修改 => '装扮修改',
        self::URL_ALL_装扮分类修改 => '装扮分类修改',
        self::URL_ALL_装扮分类上下架切换 => '装扮分类上下架切换',
        self::URL_ALL_装扮上下架切换 => '装备上下架切换',
        self::URL_ALL_房间背景选择列表 => '房间背景选择列表',
        self::URL_ALL_装扮图片上传 => '装扮图片上传',
        self::URL_ALL_房间背景修改 => '房间背景修改',
        self::URL_ALL_房间分类列表 => '房间分类列表',
        self::URL_ALL_房间分类状态修改 => '房间分类状态修改',
        self::URL_ALL_分类显示状态修改 => '分类显示状态修改',
        self::URL_ALL_渠道列表 => '渠道列表',
        self::URL_ALL_获取邀请码 => '获取邀请码',
        self::URL_ALL_获取下级渠道列表 => '获取下级渠道列表',
        self::URL_ALL_更新渠道信息 => '更新渠道信息',
        self::URL_ALL_渠道新增统计 => '渠道新增统计',
        self::URL_ALL_归属查询 => '归属查询',
        self::URL_ALL_消费统计 => '消费统计',
        self::URL_ALL_用户消费明细 => '用户消费明细',
        self::URL_ALL_每日充值用户列表 => '每日充值用户列表',
        self::URL_ALL_添加公会首页房间 => '添加工会首页房间',
        self::URL_ALL_取消公会首页房间 => '取消工会首页房间',
        self::URL_ALL_用户剩余豆 => '用户剩余豆',
        self::URL_ALL_充值人数 => '充值人数',
        self::URL_ALL_宝箱爆奖率 => '宝箱爆奖率',
        self::URL_ALL_礼物明细 => '礼物明细',
        self::URL_ALL_金宝箱 => '金宝箱',
        self::URL_ALL_消费分析 => '消费分析',
        self::URL_ALL_宝箱开奖记录 => '宝箱开奖记录',
        self::URL_ALL_开箱明细 => '开箱明细',
        self::URL_ALL_线上渠道数据列表 => '线上渠道数据列表',
        self::URL_ALL_渠道详情列表 => '渠道详情列表',
        self::URL_ALL_红包规则列表 => '红包规则列表',
        self::URL_ALL_留存 => '留存',
        self::URL_ALL_红包列表 => '红包列表',
        self::URL_ALL_红包详情列表 => '红包详情列表',
        self::URL_ALL_红包金额设置 => '红包金额设置',
        self::URL_ALL_任务添加 => '任务添加',
        self::URL_ALL_任务修改 => '任务修改',
        self::URL_ALL_主播开播时长与流水 => '主播开播时长与流水',
        self::URL_ALL_用户充值总金额 => '用户充值总金额',
        self::URL_ALL_用户许愿石详情 => '用户许愿石详情',
        self::URL_ALL_随机匹配房间 => '随机匹配房间',
        self::URL_ALL_添加随机匹配房间 => '添加随机匹配房间',
        self::URL_ALL_删除随机匹配房间 => '删除随机匹配房间',
        self::URL_ALL_新手任务列表 => '新手任务列表',
        self::URL_ALL_热云 => '热云',
        self::URL_ALL_热云详情 => '热云详情',
        self::URL_ALL_热云推广详情 => '热云推广详情',
        self::URL_ALL_新手任务更新 => '新手任务更新',
        self::URL_ALL_每日任务列表 => '每日任务列表',
        self::URL_ALL_每日任务更新 => '每日任务更新',
        self::URL_ALL_签到任务列表 => '签到任务列表',
        self::URL_ALL_签到任务更新 => '签到任务更新',
        self::URL_ALL_日常任务列表 => '日常任务列表',
        self::URL_ALL_日常任务更新 => '日常任务更新',
        self::URL_ALL_VIP订单 => 'VIP订单',
        self::URL_ALL_虚拟币流水 => '虚拟币流水',
        self::URL_ALL_用户手机号 => '用户手机号',
        self::URL_ALL_删除用户手机号 => '删除用户手机号',
        self::URL_ALL_用户留存 => '用户留存',
        self::URL_ALL_用户留存详情 => '用户留存详情',
        self::URL_ALL_删除数据 => '删除数据',
        self::URL_ALL_删除数据页 => '删除数据页',
        self::URL_ALL_删除房间名 => '删除房间名',
        self::URL_ALL_房间模式名称 => '房间模式名称',
        self::URL_ALL_金币抽奖奖励金币 => '金币抽奖奖励金币',
        self::URL_ALL_添加金币抽奖奖励金币 => '添加金币抽奖奖励金币',
        self::URL_ALL_删除金币抽奖奖励金币 => '删除金币抽奖奖励金币',
        self::URL_ALL_修改金币抽奖奖励金币 => '修改金币抽奖奖励金币',
        self::URL_ALL_金币抽奖奖励装扮 => '金币抽奖奖励装扮',
        self::URL_ALL_添加金币抽奖奖励装扮 => '添加金币抽奖奖励装扮',
        self::URL_ALL_修改金币抽奖奖励装扮 => '修改金币抽奖奖励装扮',
        self::URL_ALL_删除金币抽奖奖励装扮 => '删除金币抽奖奖励装扮',
        self::URL_ALL_金币抽奖奖励礼物 => '金币抽奖奖励礼物',
        self::URL_ALL_添加金币抽奖奖励礼物 => '添加金币抽奖奖励礼物',
        self::URL_ALL_修改金币抽奖奖励礼物 => '修改金币抽奖奖励礼物',
        self::URL_ALL_删除金币抽奖奖励礼物 => '删除金币抽奖奖励礼物',
        self::URL_ALL_房间标签 => '房间标签',
        self::URL_ALL_获取房间分类 => '获取房间分类',
        self::URL_ALL_添加房间标签 => '添加房间标签',
        self::URL_ALL_金币礼物 => '金币礼物',
        self::URL_ALL_添加金币礼物 => '添加金币礼物',
        self::URL_ALL_修改金币礼物 => '修改金币礼物',
        self::URL_ALL_清除金币礼物缓存 => '清除金币礼物缓存',
        self::URL_ALL_添加金币礼物图片 => '添加金币礼物图片',
        self::URL_ALL_金币装扮 => '金币装扮',
        self::URL_ALL_金币装扮分类 => '金币装扮分类',
        self::URL_ALL_添加金币装扮 => '添加金币装扮',
        self::URL_ALL_金币装扮图片上传 => '金币装扮图片上传',
        self::URL_ALL_金币装扮上下架切换 => '金币装扮上下架切换',
        self::URL_ALL_修改金币装扮 => '修改金币装扮',
        self::URL_ALL_金币抽奖列表 => '金币抽奖列表',
        self::URL_ALL_礼物盒子展示 => '礼物盒子展示',
        self::URL_ALL_礼物盒子添加 => '礼物盒子添加',
        self::URL_ALL_礼物盒子删除 => '礼物盒子删除',
        self::URL_ALL_装扮图片添加 => '装扮图片添加',
        self::URL_ALL_礼物盒子清除缓存 => '礼物盒子清除缓存',
        self::URL_ALL_删除监控模式 => '删除监控模式',
        self::URL_ALL_添加金币记录 => '添加金币记录',
        self::URL_ALL_增减金币 => '增减金币',
        self::URL_ALL_戳一戳配词列表 => '戳一戳配词列表',
        self::URL_ALL_戳一戳配词添加 => '戳一戳配词添加',
        self::URL_ALL_戳一戳配词删除 => '戳一戳配词删除',
        self::URL_ALL_戳一戳清除缓存 => '戳一戳清除缓存',
        self::URL_ALL_打招呼消息列表 => '打招呼消息列表',
        self::URL_ALL_打招呼消息添加 => '打招呼消息添加',
        self::URL_ALL_打招呼消息删除 => '打招呼消息删除',
        self::URL_ALL_打招呼消息清除缓存 => '打招呼消息清除缓存',
        self::URL_ALL_添加房间分类图标 => '添加房间分类图标',
        self::URL_ALL_添加房间分类 => '添加房间分类',
        self::URL_ALL_删除房间分类 => '删除房间分类',
        self::URL_ALL_添加顶级房间分类 => '添加顶级房间分类',
        self::URL_ALL_表情包列表 => '表情包列表',
        self::URL_ALL_随机头像列表 => '随机头像列表',
        self::URL_ALL_随机头像添加 => '随机头像添加',
        self::URL_ALL_随机头像删除 => '随机头像删除',
        self::URL_ALL_随机头像清除缓存 => '随机头像清除缓存',
        self::URL_ALL_表情添加 => '表情添加',
        self::URL_ALL_表情删除 => '表情删除',
        self::URL_ALL_表情编辑 => '表情编辑',
        self::URL_ALL_表情缓存清除 => '表情缓存清除',
        self::URL_ALL_修改数据 => '修改数据',
        self::URL_ALL_修改数据展示 => '修改数据展示',
        self::URL_ALL_删除渠道管理员 => '删除渠道管理员',
        self::URL_ALL_三级渠道列表 => '三级渠道列表',
        self::URL_ALL_房间内首冲曝光点击 => '房间内首冲曝光点击',
        self::URL_ALL_表情图修改 => '表情图修改',
        self::URL_ALL_敏感词展示 => '敏感词展示',
        self::URL_ALL_敏感词添加 => '敏感词添加',
        self::URL_ALL_敏感词删除 => '敏感词删除',
        self::URL_ALL_敏感词清除缓存 => '敏感词清除缓存',
        self::URL_ALL_聊天记录 => '聊天记录',
        self::URL_ALL_聊天详情 => '聊天详情',
        self::URL_ALL_获取渠道ID => '获取渠道ID',
        self::URL_ALL_渠道用户分组 => '渠道用户分组',
        self::URL_ALL_用户礼物列表 => '用户礼物列表',
        self::URL_ALL_三级渠道 => '三级渠道',
        self::URL_ALL_飞行棋 => '飞行棋',
        self::URL_ALL_飞行棋奖池 => '飞行棋奖池',
        self::URL_ALL_飞行棋奖池编辑 => '飞行棋奖池编辑',
        self::URL_ALL_飞行棋奖池清除缓存 => '飞行棋奖池清除缓存',
        self::URL_ALL_矿石礼物 => '矿石礼物',
        self::URL_ALL_矿石礼物编辑 => '矿石礼物编辑',
        self::URL_ALL_奖池比例 => '奖池比例',
        self::URL_ALL_奖池比例编辑 => '矿石兑换礼物编辑',
        self::URL_ALL_点击隐藏显示青少年模式 => '点击隐藏显示青少年模式',
        self::URL_ALL_点击分类 => '点击分类',
        self::URL_ALL_cp和游戏 => 'cp和游戏',
        self::URL_ALL_点击匹配 => '点击匹配',
        self::URL_ALL_点击动态 => '点击动态',
        self::URL_ALL_首页去找他 => '首页去找他',
        self::URL_ALL_首页大厅 => '首页大厅',
        self::URL_ALL_打招呼 => '打招呼',
        self::URL_ALL_戳一下 => '戳一下',
        self::URL_ALL_发布动态 => '发布动态',
        self::URL_ALL_添加矿石礼物位置 => '添加矿石礼物位置',
        self::URL_ALL_移除矿石礼物位置 => '移除矿石礼物位置',
        self::URL_ALL_飞行棋奖励列表 => '飞行棋奖励列表',
        self::URL_ALL_飞行棋兑换记录 => '飞行棋兑换记录',
        self::URL_ALL_飞行棋房间赠礼 => '飞行棋房间赠礼',
        self::URL_ALL_幸运盒子爆率 => '幸运盒子爆率',
        self::URL_ALL_添加虚拟用户 => '添加虚拟用户',
        self::URL_ALL_飞行棋图片 => '飞行棋图片',
        self::URL_ALL_用户邀请码添加 => '用户邀请码添加',
        self::URL_ALL_用户流失 => '用户流失',
        self::URL_ALL_修改用户礼物数量 => '修改用户礼物数量',
        self::URL_ALL_幸运盒子详情 => '幸运盒子详情',
        self::URL_ALL_用户背包礼物添加 => '用户背包礼物添加',
        self::URL_ALL_新实名认证列表 => '新实名认证列表',
        self::URL_ALL_用户体力 => '用户体力',
        self::URL_ALL_添加用户体力 => '添加用户体力',
        self::URL_ALL_三封列表 => '三封列表',
        self::URL_ALL_三封编辑 => '三封编辑',
        self::URL_ALL_游戏列表 => '游戏列表',
        self::URL_ALL_游戏开关 => '游戏开关',
        self::URL_ALL_用户注销列表 => '用户注销列表',
        self::URL_ALL_用户注销操作 => '用户注销操作',
        self::URL_ALL_用户注销取消操作 => '用户注销取消操作',
        self::URL_ALL_广告自动化时间 => '广告自动化时间',
        self::URL_ALL_爵位列表 => '爵位列表',
        self::URL_ALL_爵位添加 => '爵位添加',
        self::URL_ALL_爵位详情 => '爵位详情',
        self::URL_ALL_爵位编辑 => '爵位编辑',
        self::URL_ALL_爵位用户 => '爵位用户',
        self::URL_ALL_爵位用户添加 => '爵位用户添加',
        self::URL_ALL_后台装备管理 => '后台装备管理',
        self::URL_ALL_sql展示 => 'sql展示',
        self::URL_ALL_sql执行 => 'sql执行',
        self::URL_ALL_房间魅力值榜单 => '房间魅力值榜单',
        self::URL_ALL_房间魅力值周榜单 => '房间魅力值周榜单',
        self::URL_ALL_房间财富值榜单 => '房间财富值榜单',
        self::URL_ALL_房间财富值周榜单 => '房间财富值周榜单',
        self::URL_ALL_指定封禁功能列表 => '指定封禁功能列表',
        self::URL_ALL_指定封禁功能添加 => '指定封禁功能添加',
        self::URL_ALL_送礼飘屏 => '送礼飘屏',
        self::URL_ALL_修改送礼飘屏 => '修改送礼飘屏',
        self::URL_ALL_新三封编辑 => '新三封编辑',
        self::URL_ALL_用户登录记录 => '用户登录记录',
        self::URL_ALL_添加房间靓号 => '添加房间靓号',
        self::URL_ALL_设置房间默认背景图 => '设置房间默认背景图',
        self::URL_ALL_爵位清除缓存 => '爵位清除缓存',
        self::URL_ALL_设备黑名单 => '设备黑名单',
        self::URL_ALL_身份证黑名单 => '身份证黑名单',
        self::URL_ALL_房間分類排序 => '房間分類排序',
        self::URL_ALL_周星财富列表 => '周星财富列表',
        self::URL_ALL_添加财富周星 => '添加财富周星',
        self::URL_ALL_编辑财富周星 => '编辑财富周星',
        self::URL_ALL_月魅力列表 => '月魅力列表',
        self::URL_ALL_添加月魅力 => '添加月魅力',
        self::URL_ALL_编辑月魅力 => '编辑月魅力',
        self::URL_ALL_商品配置 => '商品配置',
        self::URL_ALL_商品编辑 => '商品编辑',
        self::URL_ALL_商品添加 => '商品添加',
        self::URL_ALL_商品详情 => '商品详情',
        self::URL_ALL_商品详情修改 => '商品详情修改',
        self::URL_ALL_商城列表 => '商城列表',
        self::URL_ALL_商城列表添加 => '商城列表添加',
        self::URL_ALL_商城配置第一层 => '商城配置第一层',
        self::URL_ALL_商城配置第二层 => '商城配置第二层',
        self::URL_ALL_商城添加商品 => '商城添加商品',
        self::URL_ALL_删除商城商品 => '删除商城商品',
        self::URL_ALL_礼物配置 => '礼物配置',
        self::URL_ALL_礼物配置添加 => '礼物配置添加',
        self::URL_ALL_礼物配置删除 => '礼物配置删除',
        self::URL_ALL_礼物配置保存 => '礼物配置保存',
        self::URL_ALL_礼物配置文件 => '礼物配置文件',
        self::URL_ALL_礼物面板 => '礼物面板',
        self::URL_ALL_礼物面板详情 => '礼物面板详情',
        self::URL_ALL_礼物商城分类添加 => '礼物商城分类添加',
        self::URL_ALL_礼物面板添加 => '礼物面板添加',
        self::URL_ALL_代充用户列表 => '代充用户列表',
        self::URL_ALL_添加代充用户 => '添加代充用户',
        self::URL_ALL_删除代充用户 => '删除代充用户',
        self::URL_ALL_删除面板礼物 => '删除面板礼物',
        self::URL_ALL_礼物商城初始化 => '礼物商城初始化',
        self::URL_ALL_礼物商城 => '礼物商城',
        self::URL_ALL_礼物商城详情 => '礼物商城详情',
        self::URL_ALL_添加礼物面板礼物 => '添加礼物面板礼物',
        self::URL_ALL_删除礼物面板礼物 => '删除礼物面板礼物',
        self::URL_ALL_装扮配置 => '装扮配置',
        self::URL_ALL_添加装扮配置 => '添加装扮配置',
        self::URL_ALL_删除装扮配置 => '删除装扮配置',
        self::URL_ALL_编辑装扮配置 => '编辑装扮配置',
        self::URL_ALL_表情包配置 => '表情包配置',
        self::URL_ALL_表情包配置添加 => '表情包配置添加',
        self::URL_ALL_表情包配置编辑 => '表情包配置编辑',
        self::URL_ALL_表情包配置删除 => '表情包配置删除',
        self::URL_ALL_表情包面板 => '表情包面板',
        self::URL_ALL_表情包面板详情 => '表情包面板详情',
        self::URL_ALL_添加表情包面板 => '添加表情包面板',
        self::URL_ALL_删除表情包面板 => '删除表情包面板',
        self::URL_ALL_红包活动 => '红包活动',
        self::URL_ALL_添加红包活动 => '添加红包活动',
        self::URL_ALL_三人夺宝奖池 => '三人夺宝奖池',
        self::URL_ALL_三人夺宝奖池礼物 => '三人夺宝奖池礼物',
        self::URL_ALL_三人夺宝奖池添加礼物 => '三人夺宝奖池添加礼物',
        self::URL_ALL_三人夺宝奖池删除礼物 => '三人夺宝奖池删除礼物',
        self::URL_ALL_红包活动礼物 => '红包活动礼',
        self::URL_ALL_红包活动礼物添加 => '红包活动礼物添加',
        self::URL_ALL_红包活动礼物删除 => '红包活动礼物删除',
        self::URL_ALL_渠道详情 => '渠道详情',
        self::URL_ALL_渠道付费用户 => '渠道付费用户',
        self::URL_ALL_工会充值用户 => '工会充值用户',
        self::URL_ALL_礼物墙开关展示 => '礼物墙开关展示',
        self::URL_ALL_礼物墙开关修改 => '礼物墙开关修改',
        self::URL_ALL_三人夺宝产出 => '三人夺宝产出',
        self::URL_ALL_流失用户 => '流失用户',
        self::URL_ALL_缓存配置 => '缓存配置',
        self::URL_ALL_瓜分番茄豆 => '瓜分番茄豆',
        self::URL_ALL_瓜分番茄豆编辑 => '瓜分番茄豆编辑',
        self::URL_ALL_商城配置第二层添加 => '商城配置第二层添加',
        self::URL_ALL_爵位配置 => '爵位配置',
        self::URL_ALL_爵位配置添加 => '爵位配置添加',
        self::URL_ALL_爵位详情配置 => '爵位详情配置',
        self::URL_ALL_每日任务配置 => '每日任务配置',
        self::URL_ALL_会员配置 => '会员配置',
        self::URL_ALL_淘金配置 => '淘金配置',
        self::URL_ALL_淘金数据列表 => '淘金数据列表',
        self::URL_ALL_淘金详情 => '淘金详情',
        self::URL_ALL_新手任务配置 => '新手任务配置',
        self::URL_ALL_金币抽奖配置 => '金币抽奖配置',
        self::URL_ALL_等级配置 => '等级配置',
        self::URL_ALL_活跃度奖励配置 => '活跃度奖励配置',
        self::URL_ALL_活跃度宝箱奖励详情配置 => '活跃度宝箱奖励详情配置',
        self::URL_ALL_宝箱配置 => '宝箱配置',
        self::URL_ALL_宝箱配置保存 => '宝箱配置保存',
        self::URL_ALL_充值配置 => '充值配置',
        self::URL_ALL_充值面板配置 => '充值面板配置',
        self::URL_ALL_登录任务配置 => '登录任务配置',
        self::URL_ALL_跑量列表 => '跑量列表',
        self::URL_ALL_跑量添加 => '跑量添加',
        self::URL_ALL_跑量导出 => '跑量导出',
        self::URL_ALL_跑量充值详情 => '跑量充值详情',
        self::URL_ALL_跑量删除 => '跑量删除',
        self::URL_ALL_跑量编辑 => '跑量编辑',
        self::URL_ALL_跑量用户id导出 => '跑量用户id导出',
        self::URL_ALL_mua新厅推荐 => 'mua新厅推荐',
        self::URL_ALL_mua新厅推荐保存 => 'mua新厅推荐保存',
        self::URL_ALL_mua房间金刚位 => 'mua房间金刚位',
        self::URL_ALL_配置展示页面 => '配置展示页面',
        self::URL_ALL_重构初始化 => '重构初始化',
        self::URL_ALL_跑量留存导出 => '跑量留存导出',
        self::URL_ALL_跑量详情 => '跑量详情',
        self::URL_ALL_跑量配置 => '跑量配置',
        self::URL_ALL_添加跑量 => '添加跑量',
        self::URL_ALL_推广渠道列表 => '推广渠道列表',
        self::URL_ALL_推广渠道新增 => '推广渠道新增',
        self::URL_ALL_推广房间列表 => '渠道新增推广房间',
        self::URL_ALL_渠道新增推广房间 => '渠道新增推广房间',
        self::URL_ALL_渠道新增推广场次 => '渠道新增推广场次',
        self::URL_ALL_推广场次配置 => '推广场次配置',
        self::URL_ALL_用户回归活动 => '用户回归活动',
        self::URL_ALL_用户回归活动编辑 => '用户回归活动编辑',
        self::URL_ALL_万千宠爱奖励配置 => '万千宠爱奖励配置',
        self::URL_ALL_周星活动 => '周星活动',
        self::URL_ALL_添加周星奖励 => '添加周星奖励',
        self::URL_ALL_编辑万千宠爱奖励 => '编辑万千宠爱奖励',
        self::URL_ALL_用户登录信息列表 => '用户登录信息列表',
        self::URL_ALL_君临天下奖励配置 => '君临天下奖励配置',
        self::URL_ALL_月榜奖励配置 => '月榜奖励配置',
        self::URL_ALL_宝箱 => '宝箱',
        self::URL_ALL_添加宝箱 => '添加宝箱',
        self::URL_ALL_宝箱奖池 => '宝箱奖池',
        self::URL_ALL_添加奖池 => '添加奖池',
        self::URL_ALL_编辑宝箱奖池 => '编辑宝箱奖池',
        self::URL_ALL_编辑奖池 => '编辑奖池',
        self::URL_ALL_宝箱爆率 => '宝箱爆率',
        self::URL_ALL_公屏和跑马灯 => '公屏和跑马灯',
        self::URL_ALL_保存公屏和跑马灯 => '保存公屏和跑马灯',
        self::URL_ALL_砸蛋详情 => '砸蛋详情',
        self::URL_ALL_指定宝箱礼物 => '指定宝箱礼物',
        self::URL_ALL_添加指定宝箱礼物 => '添加指定宝箱礼物',
        self::URL_ALL_取消指定宝箱礼物 => '取消指定宝箱礼物',
        self::URL_ALL_实时爆率 => '实时爆率',
        self::URL_ALL_宝箱上线 => '宝箱上线',
        self::URL_ALL_刷新宝箱奖池 => '刷新宝箱奖池',
        self::URL_ALL_获取奖池剩余 => '获取奖池剩余',
        self::URL_ALL_指定转盘礼物 => '指定转盘礼物',
        self::URL_ALL_添加指定转盘礼物 => '添加指定转盘礼物',
        self::URL_ALL_取消指定转盘礼物 => '取消指定转盘礼物',
        self::URL_ALL_转盘配置 => '转盘配置',
        self::URL_ALL_添加转盘 => '添加转盘',
        self::URL_ALL_编辑转盘 => '编辑转盘',
        self::URL_ALL_转盘上线 => '转盘上线',
        self::URL_ALL_获取转盘奖池礼物 => '获取转盘奖池礼物',
    ];

    /*
     * 路由
     */
    const URL_登录页面 = '/admin/loginIndex?master_url=/admin/loginIndex';
    const URL_登录操作 = '/admin/login?master_url=/admin/login';
    const URL_公共首页 = '/admin/index?master_url=/admin/index';
    const URL_控制台 = '/admin/indexConsole?master_url=/admin/indexConsole';
    const URL_菜单列表 = '/admin/getMenuLists?master_url=/admin/getMenuLists';
    const URL_菜单添加 = '/admin/addMenuItems?master_url=/admin/addMenuItems';
    const URL_图表 = '/admin/chartuser?master_url=/admin/chartuser';

    const URL_MAP = [
        self::URL_登录页面 => '/admin/loginIndex',
        self::URL_登录操作 => '/admin/login',
        self::URL_公共首页 => '/admin/index',
        self::URL_控制台 => '/admin/indexConsole',
        self::URL_菜单列表 => '/admin/getMenuLists',
        self::URL_菜单添加 => '/admin/addMenuItems',
        self::URL_图表 => '/admin/chartuser',
    ];
}
